export const GET_CITIES = "GET_CITIES";
export const CITIES_LOADING = 'CITIES_LOADING';

export const GET_ITINERARIES = "GET_ITINERARIES";
export const ITINERARIES_LOADING = "ITINERARIES_LOADING";

export const POST_USER = "POST_USER";
export const USER_LOADING = "USER_LOADING";